FROM debian
ADD debian.list /etc/apt/sources.list.d/
RUN apt-get update && \
    apt-get -y upgrade && \
    apt -y install nginx && \
    apt-get clean && \
    rm -rf /var/www/* && \ 
    mkdir -p /var/www/zeph1rr.com/img && \
    chmod -R 754 /var/www/zeph1rr.com/ && \
    useradd zeph1rr && groupadd grihan &&\
    usermod -aG grihan zeph1rr && \
    chown -R zeph1rr:grihan /var/www/zeph1rr.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/zeph1rr.com/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user zeph1rr/g' /etc/nginx/nginx.conf
ADD index.html /var/www/zeph1rr.com/
ADD img.jpg /var/www/zeph1rr.com/img/
CMD ["nginx", "-g", "daemon off;"]
