FROM debian
ADD debian.list /etc/apt/sources.list.d/
RUN apt-get update && \
    apt-get -y upgrade && \
    apt -y install nginx && \
    apt-get clean && \
    rm -rf /var/www/* && \ 
    mkdir -p /var/www/slavya.com/img && \
    chmod -R 754 /var/www/slavya.com/ && \
    useradd slavya && groupadd nochka &&\
    usermod -aG nochka slavya && \
    chown -R slavya:nochka /var/www/slavya.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/slavya.com/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user slavya/g' /etc/nginx/nginx.conf
ADD index.html /var/www/slavya.com/
ADD img.jpg /var/www/slavya.com/img/
CMD ["nginx", "-g", "daemon off;"]
